using IFY.Phorm.Execution;

namespace IFY.Phorm.Data;

/// <summary>
/// Represents a contract member that provides access to console messages generated by a stored procedure.
/// </summary>
public sealed class ConsoleLogMember : ContractMember
{
    /// <summary>
    /// Console messages produced by the stored procedure.
    /// </summary>
    public new ConsoleMessage[] Value => (ConsoleMessage[])base.Value!;

    internal ConsoleLogMember()
        : base("console", Array.Empty<ConsoleMessage>(), ParameterType.Console, typeof(ConsoleMessage[]))
    {
    }
}
